# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate mqr-dev
#
name: mqr-dev
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - ipython
  - notebook
  - pip
  - pytest
  - markdown=3.6,
  - matplotlib=3.8.0,
  - mergedeep=1.3.4,
  - numpy=1.26.4
  - openpyxl=3.1.2
  - pandas=2.2.2
  - probscale=0.2.5,
  - pydoe3=1.0.3
  - rich=13.3.5
  - scipy=1.13.1
  - seaborn=0.13.2
  - statsmodels=0.14.1
